on: [push]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd ./ilc/
        docker build . --file Dockerfile --tag stylet/ilc:latest
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username foo --password-stdin
        docker push stylet/ilc:latest
