on: [push]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: jerray/publish-docker-action@d035a9e
      with:
        username: StyleT
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: stylet/icl/ilc
        path: ./ilc/
        file: ./ilc/Dockerfile
        auto_tag: true
        allow_pull_request: true
#    - name: Build the Docker image
#      run: |
#        cd ./ilc/
#        docker build . --file Dockerfile --tag stylet/ilc:latest
#        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username stylet --password-stdin
#        docker push stylet/ilc:latest
