on: [push]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Calc tags
      id: tags
      run: |
        BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-99)
        TAGS=$([ "$BRANCH" == "feature/docker_build" ] && echo "latest," || echo "")
        echo ::set-output name=docker_tags::$TAGS${GITHUB_SHA:0:7}

    - uses: jerray/publish-docker-action@d035a9e
      with:
        username: StyleT
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: stylet/icl/ilc
        path: ./ilc/
        file: ./ilc/Dockerfile
#        auto_tag: true
        tags: ${{ steps.tags.outputs.docker_tags }}
        allow_pull_request: true
#    - name: Build the Docker image
#      run: |
#        cd ./ilc/
#        echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username stylet --password-stdin
#        docker build . --file Dockerfile --tag docker.pkg.github.com/stylet/icl/ilc:latest
#        docker push docker.pkg.github.com/stylet/icl/ilc:latest
